coolsite/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('<int:page>/', index, name='home'),
    path('about', about, name='about'),
    path('feedback', feedback, name='feedback'),
    path('one/<int:pid>/', one, name='one'),
    path('leet/', leet, name='leet'),
    path('translit/', translit, name='translit'),
#    re_path(r'^/?pYear/')
]

coolsite/coolsite/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from coolsite import settings
from women.views import *

app_name = 'women'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('women.urls', 'women'), namespace='women')),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/',include('debug_toolbar.urls')),
    ] + urlpatterns

    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT);

    urlpatterns += [
        path('captcha/', include('captcha.urls')),
    ]

handler404 = pageNotFound;

coolsite/women/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import  cache_page

from .views import *

urlpatterns = [
    path('', cache_page(60)(WomenHome.as_view()), name='home'),
    path('category/<slug:cat_slug>/', WomenCategory.as_view(), name='category'),
    path('addpage', AddPage.as_view(), name='add_page'),
    path('about', about, name='about'),
    path('contact', ContactFormView.as_view(), name='contact'),
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('register', RegisterUser.as_view(), name='register'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),

]

coolsite/women/models.py
from django.db import models
from django.urls import reverse

class Women(models.Model):
    title = models.CharField(max_length=255, verbose_name="Имя")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Содержимое")
    birthday = models.DateField(null=True, blank=True, verbose_name="День рождения")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", null=True, blank=True, verbose_name="Фото")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Изменено")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT,  verbose_name="Категория")
    foreign_agency = models.BooleanField(default=False, verbose_name="Признана иностранным агентом")

    class Meta:
        verbose_name = 'Известные женщины'
        verbose_name_plural = 'Известные женщины'
        ordering = ['id']

    def __str__(self):
        return self.title;

    def get_absolute_url(self):
        return reverse('women:post', kwargs={'post_slug':self.slug});

    def get_item_url(self):
        return reverse('women:post', kwargs={'post_id':self.pk});

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    def __str__(self):
        return self.name;

    def get_absolute_url(self):
        return reverse('women:category', kwargs={'cat_slug':self.slug});

coolsite/women/forms.py
from captcha.fields import CaptchaField, CaptchaTextInput
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import *
from django.core.exceptions import ValidationError

class AddPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категория не выбрана"

    class Meta:
        model = Women
        fields = ['title','slug','content','birthday','photo','cat','is_published']#'__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-input'}),
            'content': forms.Textarea(attrs={'cols':60, 'rows':10})
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 100:
            raise ValidationError('Длина превышает 100 символов')

        return title

class RegisterUserForm(UserCreationForm):

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class':'form-input'}))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class':'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class ContactForm(forms.Form):
    username = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'cols': 60, 'rows':10}))
    captcha = CaptchaField(label="Проверочный код ", widget=CaptchaTextInput(attrs={}))

coolsite/women/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from time import strftime

from django.urls import reverse_lazy

from women.forms import *
from django.views.generic import ListView, DetailView, CreateView, FormView
from .models import *
from .utils import *
from django.contrib.auth.mixins import LoginRequiredMixin

class WomenHome(DataListMixin, ListView):
    model = Women
    paginate_by = 4
    template_name = 'women/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_basic_data(title='Главная страница')
        return {**context, **c_def}

    def get_queryset(self):
        return Women.objects.filter(is_published=True).select_related('cat')


class WomenCategory(DataListMixin, ListView):
    model = Women
    paginate_by = 4
    template_name = 'women/index.html'
    context_object_name = 'posts'
    allow_empty = True
    #extra_context = {'title':'Главная страница'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        categ = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_basic_data(title='Категория: '+categ.name, cat_slug_selected=categ.slug)
        #context['cat_slug_selected']= self.kwargs['cat_slug'];
        return {**context, **c_def}

    def get_queryset(self):
        return Women.objects.filter(is_published=True, cat__slug=self.kwargs['cat_slug']).select_related('cat')

class ShowPost(DataMixin, DetailView):
    model = Women
    template_name = 'women/post.html'
    context_object_name = 'w'
    allow_empty = False
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
    #    context['title'] = context['w']
        context['cat_slug_selected'] = context['w'].cat.slug
        context['strftime']=strftime
        c_def = self.get_basic_data(title=context['w'])
        return {**context, **c_def}
  #      return context

class AddPage(LoginRequiredMixin, DataMixin,CreateView):
    form_class = AddPostForm
    template_name = 'women/addpage.html'
    # LoginRequiredMixin
    success_url = reverse_lazy('women:home')
    login_url = reverse_lazy('women:home')
    # redirect_field_name = 'redirect_to'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_basic_data(title='Добавление статьи')
        return {**context, **c_def}

# @login_required
def about(request):
    paginator = Paginator(Women.objects.all(),3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'women/about.html', { 'menu':menu, 'page_obj':page_obj, 'title': 'О сайте'})

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'women/register.html'
    success_url = reverse_lazy('women:login')
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_basic_data(title='Регистрация')
        return {**context, **c_def}

class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'women/login.html'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_basic_data(title='Авторизация')
        return {**context, **c_def}

    def get_success_url(self):
        return reverse_lazy('women:home')

def logout_user(request):
    logout(request)
    return redirect('women:login')

class ContactFormView(DataMixin, FormView):
    form_class = ContactForm
    template_name = 'women/contact.html'
    success_url = reverse_lazy('women:home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_basic_data(title='Обратная связь')
        return {**context, **c_def}

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('women:home')


def login(request):
    return render(request, 'women/about.html', { 'title': 'Войти'})

def archive(request, year):
    if int(year) > 2020:
        return redirect('home', permanent=False)

    return HttpResponse(f"<h1>Архив по годам</h1><p>{year}</p>")

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

coolsite/women/templates/women/about.html
{% extends 'women/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Содержимое страницы о сайте</p>
{% endblock %}

coolsite/women/templates/women/addpage.html
{% extends 'women/base.html' %}
{% load static %}
{% block content %}

<form method="post" action="{% url 'women:add_page' %}" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label> {{ f }}</p>
    {% endfor %}

    <div class="form-error">{{ form.title.errors }}</div>

    <input type="submit" value="Добавить" />
</form>

{% endblock %}

coolsite/women/templates/women/base.html
{% load static %}
{% load women_tags %}
{% load cache %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" width="100%" height="100%" border=0 cellpadding="0" cellspacing="0">
{% cache 120 header %}
<tr style="height:60px;">
	<td valign=top colspan="2">
		<div class="header">
		<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"><img src="{% static 'women/img/logo.png' %}" /></div></a></li>
			{% for mi in menu %}
				<li><a href="{% url mi.url %}">{{ mi.title }}</a></li>
			{% endfor %}

			{% if request.user.is_authenticated %}
				<li class="last" >
					{{ user.username }} |
					<a href="{% url 'women:logout' %}">Выйти</a>
				</li>
			{% else %}
				<li class="last" >
					<a href="{% url 'women:register' %}">Регистрация</a>
				</li>
				<li class="last" >
					<a href="{% url 'women:login' %}">Войти</a>
				</li>
			{% endif %}
		</ul>
		<div class="clear"></div>
		</div>
	</td>
</tr>
{% endcache %}
<tr valign="top">
	<!-- Sidebar слева -->

	<td valign="top" class="left-chapters">
		<ul id="leftchapters">

			{% categories_list 'name' cat_slug_selected=cat_slug_selected %}

			<li class="share">
				<p>Наш канал</p>
				<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
			</li>
		</ul>
	</td>

		<!-- Конец Sidebar'а -->
	<td valign="top" class="content">
			<!-- Хлебные крошки -->
			{% block breadcrumbs %}
			{% endblock %}

		<!-- Блок контента -->
			<div class="content-text">
		{% block content %}
		{% endblock %}
			</div>
		<!-- Конец блока контента -->

		</td>
</tr>
<!-- Footer -->
<tr>
	<td valign=top colspan="2">
		<div id="footer">
			<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
		</div>
	</td>
</tr>
</table>
<!-- Конец footer'а и страницы -->
</body>
</html>

coolsite/women/templates/women/contact.html
{% extends 'women/base.html' %}

{% block content %}
<div>
    <form method="post" action="{% url 'women:contact' %}" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label> {{ f }}</p>
    {% endfor %}

    <div class="form-error">{{ form.title.errors }}</div>

    <input type="submit" value="Добавить" />
    </form>
</div>



{% endblock %}

coolsite/women/templates/women/index.html
{% extends 'women/base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
		<li>
			<div class="article-panel">
				<p class="first">Категория: {{p.cat}}</p>
				<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
			</div>

			{% if p.photo %}
				<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
			{% endif %}

			<h2>{{p.title}} {% if p.foreign_agency %}<span class="foreign-agency">Признана иностранным агентом</span>{% endif %}</h2>
			{% autoescape on %}
			{{p.content|linebreaks|truncatewords:50}}
			{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
		</li>
	{% endfor %}
</ul>
{% if page_obj.has_other_pages %}
<nav class="list-pages">
	<ul>
		{% if page_obj.has_previous %}
			<li>
				<a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;</a>
			</li>
		{% endif %}

		{% if page_obj.number > 3 %}
			{% if page_obj.number == 1 %}
					<li class="page-num page-num-selected">1</li>
			{% else %}
					<li class="page-num">
						<a href="?page=1">1</a>
					</li>
			{% endif %}
		{% endif %}

		{% if page_obj.number > 4 %}
			<li>
				<span class="dots">...</span>
			</li>
		{% endif %}

		{% for p in paginator.page_range %}
			{% if p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
				{% if page_obj.number == p %}
					<li class="page-num page-num-selected">{{ p }}</li>
				{% else %}
					<li class="page-num">
						<a href="?page={{ p }}">{{ p }}</a>
					</li>
				{% endif %}
			{% endif %}
		{% endfor %}

		{% if page_obj.number < paginator.num_pages|add:-3 %}
			<li>
				<span class="dots">...</span>
			</li>
		{% endif %}

		{% if page_obj.number < paginator.num_pages|add:-2 %}
			{% if page_obj.number == paginator.num_pages %}
					<li class="page-num page-num-selected">{{ paginator.num_pages }}</li>
			{% else %}
					<li class="page-num">
						<a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
					</li>
			{% endif %}
		{% endif %}

		{% if page_obj.has_next %}
			<li >
				<a href="?page={{ page_obj.next_page_number }}">&gt;&gt;</a>
			</li>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock %}

coolsite/women/templates/women/list_categories.html
{% if cat_slug_selected == 0 %}
	<li class="selected">Все категории</li>
{% else %}
	<li><a href="{% url 'women:home' %}">Все категории</a></li>
{% endif %}

{% for cat in cats %}
	{% if cat.slug == cat_slug_selected %}
		<li class="selected">{{ cat.name }}</li>
	{% else %}
		<li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
	{% endif %}
{% endfor %}

coolsite/women/templates/women/login.html
{% extends 'women/base.html' %}

{% block content %}
<div>
    <h1>Авторизация</h1>
    <form method="post">
        {% csrf_token %}

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label> {{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <div class="form-error">{{ form.title.errors }}</div>
        <button type="submit">Войти</button>
    </form>

</div>



{% endblock %}

coolsite/women/templates/women/post.html
{% extends 'women/base.html' %}

{% block content %}
<div>
    <h1>{{w.title}}</h1>
	{% if w.birthday  %}
		<h3>Дата рождения: <span>{{ w.birthday }} </span></h3>
	{% endif %}
	{% if w.photo %}
		<img src="{{w.photo.url}}" width="300px"/>
	{% endif %}
	{% autoescape on %}
	<p class="link-read-post">{{w.content|linebreaks}}</p>
	{% endautoescape %}
			<div class="clear"></div>


</div>



{% endblock %}

coolsite/women/templates/women/register.html
{% extends 'women/base.html' %}

{% block content %}
<div>
    <h1>Регистрация</h1>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label> {{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <div class="form-error">{{ form.title.errors }}</div>
        <button type="submit">Зарегистрироваться</button>
    </form>

</div>



{% endblock %}